In [1]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
b = np.array([(1.6,2,3), (4,5,6)], dtype = bool)
print (b)


[[ True  True  True]
 [ True  True  True]]


In [6]:
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)
print(c)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [32]:
d= np.full((3,4),7)
print(d)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [34]:
np.eye((2), dtype=int)

array([[1, 0],
       [0, 1]])

In [37]:
np.random.random((2,2))

array([[0.39321629, 0.22265368],
       [0.85130148, 0.95641592]])

In [52]:
d= np.empty((3,4),dtype='f')
d.astype(int)


array([[0, 1, 0, 2],
       [0, 2, 0, 2],
       [0, 2, 0, 2]])

In [53]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [80]:
a= np.array([(4,2),(4,3)])
b=np.array([(2,3),(3,4)])
print(a)
print(b)
m= a/b
print(m)

[[4 2]
 [4 3]]
[[2 3]
 [3 4]]
[[2.         0.66666667]
 [1.33333333 0.75      ]]


In [74]:
np.log(a)

array([[1.38629436, 0.69314718],
       [1.38629436, 1.09861229]])

In [75]:
a.dot(b)

array([[14, 20],
       [17, 24]])

In [76]:
np.exp(b)

array([[ 7.3890561 , 20.08553692],
       [20.08553692, 54.59815003]])

In [81]:
a==b

array([[False, False],
       [False, False]])

In [83]:
a>3

array([[ True, False],
       [ True, False]])

In [84]:
np.array_equal(a,b)

False

In [85]:
a.sum(1)

array([6, 7])

In [87]:
a.min()

2

In [88]:
a.max()

4

In [89]:
b.max(axis=0)

array([3, 4])

In [90]:
np.std(b)

0.7071067811865476

In [91]:
np.corrcoef(b)

array([[1., 1.],
       [1., 1.]])

In [92]:
a.mean()

3.25

In [97]:
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [99]:
h= a.view()
print(h)

[[4 2]
 [4 3]]


In [100]:
np.copy(a)
h= a.copy()
print(h)

[[4 2]
 [4 3]]


In [104]:
c=a.sort(axis=0)
print(c)

None


In [112]:
a[0]

array([2, 4])

In [114]:
d= np.array([(1,2,3),(2,45,3)])
print(d)


[[ 1  2  3]
 [ 2 45  3]]


In [129]:
d[: :-1]

array([[ 2, 45,  3],
       [ 1,  2,  3]])

In [131]:
d[d<4]

array([1, 2, 3, 2, 3])